apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: foodgram
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command:
            - sh
            - -c
            - |
              echo "Waiting for Postgres to be ready..."
              until nc -z $DB_HOST $DB_PORT; do
                echo "Postgres is unavailable - sleeping"
                sleep 2
              done
              echo "Postgres is up!"
          env:
            - name: DB_HOST
              value: "postgres"
            - name: DB_PORT
              value: "5432"
      containers:
        - name: backend
          image: allay6/backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: DEBUG
              value: "0"
            - name: ALLOWED_HOSTS
              value: "127.0.0.1,localhost,nginx-service"
            - name: DB_ENGINE
              value: "django.db.backends.postgresql"
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD
            - name: DB_HOST
              value: "postgres"
            - name: DB_PORT
              value: "5432"
          volumeMounts:
            - name: media-files
              mountPath: /app/media
      volumes:
        - name: media-files
          persistentVolumeClaim:
            claimName: media-pvc
      imagePullSecrets:
        - name: regcred
