apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: {{ .Values.namespace }}
data:
  DEBUG: {{ .Values.backend.env.DEBUG | quote }}
  ALLOWED_HOSTS: {{ .Values.backend.env.ALLOWED_HOSTS | quote }}
  DB_HOST: {{ .Values.backend.env.DB_HOST | quote }}
  DB_PORT: {{ .Values.backend.env.DB_PORT | quote }}
  DB_NAME: {{ .Values.backend.secrets.db | quote }}
