apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.postgres.configMapName }}
  namespace: {{ .Values.namespace }}
data:
  DB_HOST: "postgres.{{ .Values.namespace }}.svc.cluster.local"
  DB_PORT: "5432"
