apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: {{ .Values.postgres.servicePort }}
      targetPort: {{ .Values.postgres.servicePort }}
  selector:
    app: postgres
  clusterIP: None
