apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres.secretsName }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  POSTGRES_DB: "Zm9vZGdyYW0="
  POSTGRES_USER: "YWxsYXk2"
  POSTGRES_PASSWORD: "ZnJpejIyOHh4"
