{{- if .Values.job.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.job.name }}
  namespace: {{ .Values.namespace }}
spec:
  template:
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image }}
          command: {{ toJson .Values.job.command }}
          envFrom:
            - secretRef:
                name: {{ .Values.backend.secrets.name }}
            - configMapRef:
                name: backend-config
      restartPolicy: OnFailure
{{- end }}
