apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: foodgram
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: yc-network-hdd
  resources:
    requests:
      storage: 2Gi