apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: foodgram
type: Opaque
stringData:     #переделать
  POSTGRES_DB: "Zm9vZGdyYW0="
  POSTGRES_USER: "YWxsYXk2"
  POSTGRES_PASSWORD: "ZnJpejIyOHh4"
