namespace: foodgram
createNamespace: false

backend:
  image: allay6/fg-backend
  imagePullPolicy: IfNotPresent
  replicas: 2
  containerPort: 8000
  servicePort: 8000
  targetPort: 8081
  mediaStorage: 2Gi
  env:
    DEBUG: "False"
    ALLOWED_HOSTS: "130.193.52.254,localhost,nginx-service"
    DB_ENGINE: "django.db.backends.postgresql"
    DB_HOST: "postgres"
    DB_PORT: "5432"
  secrets:
    name: postgres-secret
    db: POSTGRES_DB
    user: POSTGRES_USER
    password: POSTGRES_PASSWORD

job:
  enabled: true
  name: backend-migrate
  command: ["python", "manage.py", "migrate", "--noinput"]

ingress:
  enabled: true
  className: nginx
  host: foodgram.localhost.ru
  tls:
    enabled: true
    hosts:
      - foodgram.example.com
    secretName: foodgram-tls
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"


postgres:
  image: postgres:17
  replicas: 1
  storage: 5Gi
  pvcAccessMode: ReadWriteOnce
  servicePort: 5432
  secretsName: postgres-secret
  configMapName: postgres-config

nginx:
  image: nginx:1.25.4-alpine
  replicas: 2
  servicePort: 80
  mediaPVC: media-pvc
  configMap: nginx-config