apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "backend.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  DB_ENGINE: {{ .Values.service.env.DB_ENGINE }}
  DB_HOST: {{ .Values.service.env.DB_HOST }}
  DB_PORT: "{{ .Values.service.env.DB_PORT }}"
  DEBUG: "{{ .Values.service.env.DEBUG }}"
  ALLOWED_HOSTS: "{{ .Values.service.env.ALLOWED_HOSTS }}"