apiVersion: v1
kind: Secret
metadata:
  name: {{ default "db-secrets" .Values.secrets.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DB_USER: "{{ .Values.secrets.username }}"
  DB_PASSWORD: "{{ .Values.secrets.password }}"
  DB_NAME: "{{ .Values.secrets.database }}"
