apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.image.backend }}
          ports:
            - containerPort: 8000
          env:
            - name: DEBUG
              value: "{{ .Values.backend.debug }}"
            - name: DB_ENGINE
              value: "django.db.backends.postgresql"
            - name: DB_NAME
              value: {{ .Values.postgres.db }}
            - name: DB_USER
              value: {{ .Values.postgres.user }}
            - name: DB_PASSWORD
              value: {{ .Values.postgres.password }}
            - name: DB_HOST
              value: "postgres"
            - name: DB_PORT
              value: "5432"
