apiVersion: batch/v1
kind: Job
metadata:
  name: backend-migrate
  namespace: {{ .Values.namespace }}
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: {{ .Values.image.backend }}
          command: ["python", "manage.py", "migrate", "--noinput"]
          env:
            - name: DB_ENGINE
              value: "django.db.backends.postgresql"
            - name: DB_NAME
              value: {{ .Values.postgres.db }}
            - name: DB_USER
              value: {{ .Values.postgres.user }}
            - name: DB_PASSWORD
              value: {{ .Values.postgres.password }}
            - name: DB_HOST
              value: "postgres"
            - name: DB_PORT
              value: "5432"
