apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc-nginx
  namespace: foodgram
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard

