apiVersion: batch/v1
kind: Job
metadata:
  name: backend-migrate
  namespace: foodgram
spec:
  template:
    spec:
      containers:
        - name: backend
          image: allay6/backend:latest
          command: ["python", "manage.py", "migrate", "--noinput"]
          envFrom:
            - secretRef:
                name: postgres-secret
            - configMapRef:
                name: backend-config
      restartPolicy: OnFailure
