# Generated by Django 5.2.1 on 2025-05-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_rename_unit_ingredient_measurement_unit"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="title",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="recipe",
            old_name="description",
            new_name="text",
        ),
        migrations.AddField(
            model_name="recipe",
            name="is_favorited",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="recipe",
            name="is_in_shopping_cart",
            field=models.BooleanField(default=False),
        ),
    ]
