# Generated by Django 5.2.1 on 2025-05-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_recipe_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="slug",
            field=models.SlugField(blank=True, max_length=256, unique=True),
        ),
    ]
