# Generated by Django 5.2.1 on 2025-05-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_recipe_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipeingredient",
            name="amount",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
