# Generated by Django 5.2.1 on 2025-05-19 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0007_fix_invalid_slugs"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipe",
            options={
                "verbose_name": "рецепт",
                "verbose_name_plural": "Рецепты",
                "ordering": ["-created_at"],
            },
        )
    ]
