# Generated by Django 5.2.1 on 2025-05-20 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0008_fix_ordering_recipes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="is_favorited",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="is_in_shopping_cart",
        ),
    ]
