# Generated by Django 5.2.1 on 2025-05-16 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_favourite_recipe_favourite_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Follow",
        ),
    ]
